coopnorge/go-datadog-lib

.editorconfig
.gitattributes

https://go.dev/doc/effective_go#formatting defines that we should use tabs for
indents and there is no line length limit.

Add Go specific EditorConfig

---

boostrap_test.go
bootstrap.go
docs/index.md
metric/datadog.go
metric/datadog_test.go

- Decuple metrics and bootstrap for Datadog service from Coop logger.
- Propagate errors
- Update Documentation examples
closes #25
closes #20

Propagate errors in bootstrap and metric constructor

---

bootstrap.go

Enable by default: https://docs.datadoghq.com/tracing/metrics/runtime_metrics/

Add runtime metrics for tracer so it will be showed in Datadog

---

boostrap_test.go
bootstrap.go
config/config.go
docs/index.md

An enum encodes the meaning of its values. This removes the need to store the
value of the connection type flag in a variable to make it clear.
Configure extra profiling in `DatadogConfig` so that services to not have to
implement configuration support for this.
This is a breaking change.

Make the bootstrap API easier to use

---

boostrap_test.go
config/config.go
config/config_test.go

- Update JSON autogenerated tags to be the same as `mapstructure`. 
- Parse string to bool to support 2 ways of config loading: custom via `viper` pkg and vanilla

Update DatadogConfig parsing

---

boostrap_test.go
config/config.go
config/config_test.go

This reverts commit d51b85f2a217841c61b225f4532be551a1de65ac.
This commit broke the public API of the struct `DatadogConfig`:
- Changing the type of `EnableExtraProfiling` from `bool` to `string`
When bumping from 2.0.0 to 2.0.3 (that includes the changes introduced in
2.0.2) helloworld no longer validates
See: https://github.com/coopnorge/helloworld/actions/runs/5967664512/job/16189795843?pr=369#step:9:42
Closes: #128

Revert "Update DatadogConfig parsing (#125)"

---

README.md
internal/context.go
internal/env.go
middleware/echo/echo.go
middleware/echo/echo_test.go
middleware/grpc/grpc.go
middleware/grpc/grpc_test.go
tracing/log.go
tracing/tracing.go
tracing/tracing_test.go

Pull reguest for merging into branch `distributed_tracing` ref pr: https://github.com/coopnorge/go-datadog-lib/pull/155
Feature flagging the new features while keeping the old implementation.
only if env var `DD_EXPERIMENTAL_TRACING_ENABLED` is set to `True` you will get the new interceptor implementation.
This will make it possible to change between versions in different environments.

Feature flag experimental features

---

docker-compose/Dockerfile

Our current way of tagging Docker images is not compatible with Dependabot when
combined with a digest. Using the latest tag until we have a better versioning
scheme.
Ref:
- https://github.com/coopnorge/engineering-docker-images/issues/1253

Enable bumping devtools versions using Dependabot

---

.github/workflows/cicd.yaml

`coopnorge/github-workflow-techdocs/.github/workflows/techdocs.yaml@v0` now
requires `pull-requests: read`.

chore: Add missing GHA workflow permissions

---

.policy.yml

CI can't be required using Policy Bot. Combining GitHub status checks
and Policy Bot for approvals solves the problem.

ci: Remove wrong CI "approval" check

---

go.mod
go.sum
tracelogger/hook.go

If the hook is added to the go-logger lib, and then a log-message is logged with `logger.WithContext(ctx).Info("my-message")`, then any datadog trace-information in the context will be added to the log-message's fields.
Note: This commit will fail until go-logger has released a new version, with the HookEntry-struct.
Closes https://github.com/coopnorge/go-logger/issues/61

feat: Add Datadog hook for go-logger lib

---

middleware/grpc/client.go
middleware/grpc/options.go
middleware/grpc/server.go

Add options-pattern for configuring the grpc-server/client interceptors, and deprecate the old non-options interceptor.

feat(grpc): Add additional versions of grpc-interceptors, which are configurable

---

.markdownlint.yaml
README.md
docs/index.md
middleware/http/client.go
middleware/http/options.go
middleware/http/options_test.go

Note: when migrating from `WrapClient` to `AddTracingToClient`, you should look into which ResourceNamer is suitable for the calls you make.
The default is set to `FullURLResourceNamer`, which will produce ResourceNames like `GET https://www.coop.no/api/some-service/some-endpoint`.
If you are making calls to e.g. `https://www.coop.no/api/customer/123`, then you probably want to create a custom ResourceNamer that does not include `123`.
Closes #243

feat(http): Add additional version of http-wrapper, which is configurable

---

middleware/grpc/client.go
middleware/grpc/server.go
middleware/http/client.go
tracing/tracing.go

Deprecated comments must be preceded by a blank line or blank comment line or
it will not be detected by golangci-lint. See external example
<https://go.dev/wiki/Deprecated>.

fix: Deprecated comments

---

bootstrap.go
config/config.go
config/config_test.go

`config.IsDataDogConfigValid()` does not tell us what is wrong with the
configuration leaving the user to guess or inspect the code and configuration.
In stead we should raise errors telling the user what is wrong.
Resolves: https://github.com/coopnorge/go-datadog-lib/issues/281

feat: Add `config.Validate()`

---

middleware/gorm/gorm.go

`gormtrace.Open` call `gorm.Open` which accepts vardic options arguments.
And if config passed is nil, `gorm.Open` accepts at is a valid `Option`
and tries to call `Apply` on it an panic.
There isn't much we can do about it except for passing in a new
`Config` when gormCfg is nil.

fix: gormtrace panics when nil config is provided

---

.policy.yml

In order to reduce the notification storm that hits users when dependencies are
update select a set of random users from engineering to review rather than the
whole team.
Ref:
- https://github.com/coopnorge/go-datadog-lib/pull/324

chore: Reduce the number of users requested to review updates

---

go.mod

Ref: https://inventory.internal.coop/docs/default/component/guidelines/languages/go/#the-gomod-file

fix: Go directive should use the full version

---

boostrap_test.go
bootstrap.go

fixes: https://github.com/coopnorge/go-datadog-lib/issues/423
~~Tests need to be added.~~  Looking for some input on if this is a valid idea.

feat: auto detect connectiontype

---

integration/doc.go
integration/integration_test.go

Mostly copied from https://github.com/coopnorge/helloworld/blob/502350752fc224ad17f51b7f1a8d9c183b07f25f/helloworld/cmd/helloworld/trace_test.go, but with `google.golang.org/grpc/interop/grpc_testing` instead of helloworld gRPC contract.

test: Add integration-test for gRPC server and HTTP-client

---

docs/index.md
internal/env.go

`DD_AGENT_HOST` is currently not required, the docs should reflect this.

docs: Remove DD_AGENT_HOST info

---

bootstrap_test.go
config/config_test.go
integration/integration_test.go
legacy_bootstrap_test.go
metric/datadog_test.go
metric/metric_test.go
metrics/metrics_test.go
middleware/database/database_test.go
middleware/echo/echo_test.go
middleware/grpc/client_test.go
middleware/grpc/server_test.go
middleware/http/client_test.go
middleware/http/options_test.go
tracing/log_test.go
tracing/tracing_test.go

This change ensures that we test the behaviour of exported functions and types
in stead of implementation details.
As a consequence the tests testing `coopdatadog.StartDatadog` have been
rewritten into a table test, as a side effect test coverage has been slightly
improved.

refactor: Define tests in `_test` packages

---

.github/workflows/cicd.yaml
README.md
bootstrap.go
go.mod
go.sum
legacy_bootstrap.go
magefiles/magefile.go

This change enables CI using mage. The linting configuration found some casing
issues in a few errors messages that have been fixed at the same time.
Removing the old devtools will be done as a separate change.

chore: Use mage for CI

---

bootstrap.go
bootstrap_internal_test.go
config/config.go
docs/index.md
legacy_bootstrap.go
legacy_bootstrap_internal_test.go

Both for the legacy bootstrapper, and the new bootstrapper, we should allow both `/var/run/datadog/apm.socket` and `unix:///var/run/datadog/apm.socket`. This should help in migrating from the legacy to the new bootstrapper.

feat: Normalize "DD_TRACE_AGENT_URL" to work with both unix-scheme prefix and not.

---

metrics/metrics.go
metrics/metrics_internal_test.go
metrics/options.go
metrics/options_test.go

Use the same options-type (both the struct, and the functional argument) for the global metric options and the per-metric options. This means that we can use the same "WithSampleRate", "WithTag" etc for the global and the per-metric options. It also allows for configuring a custom errorhandler for a single metric (e.g. where it is imperative that we are able to report the metric)
Also, if an error happens during resolving of per-metric options, then the error-handler will be used (global, or successfully set with per-metric options)
This PR is stacked on #524, and will not prevent us from completing #527

refactor: Simplify metric-options

---

bootstrap.go
internal/log/log.go
internal/log/log_test.go
internal/log/option.go
legacy_bootstrap.go

This change moves the Datadog logging adapter from `go-logger` to
`go-datadog-lib`. With the recent changes to `dd-trace-go` `go-logger` should not
have a dependency on `dd-trace-go` so this is better implemented in
`go-datadog-lib` that must a dependency on `go-logger`. Nothing should use this
adapter directly outside of `go-datadog-lib` therefor it is implemented as a
internal package.

feat: Add a logging adapter for go-logger
